import { ICurrency } from "../currency/currency";
import { ICustomer } from "../customer/customer";
import { IDocumentType } from "../document-type/documentType";
import { IEstablishment } from "../establishment/establishment";
import { IPointOfSale } from "../establishment/pointOfSale";
import { IPaymentTerm } from "../payment-term/paymentTerm";
import { IUser } from "../user/user";
import { IWarehouse } from "../warehouse/warehouse";
import { ISaleInstalment } from "./instalment";
import { ISalePayment } from "./payment";
import { ISaleProduct } from "./product";

export interface ISale {
    id: number;
    customer_id: number;
    currency_id: number;
    point_of_sale_id: number;
    warehouse_id: number;
    seller_id: number;
    document_type_id: number;
    payment_term_id: number;
    billed_at: string;
    expires_at: string | null;
    paid_at: string | null;
    name: string;
    identification_document: string;
    phone: string | null;
    email: string | null;
    address: string | null;
    comments: string | null;
    created_by: number | null;
    updated_by: number | null;
    created_at: string;
    updated_at: string;
    customer: ICustomer;
    currency: ICurrency;
    establishment: IEstablishment;
    point_of_sale: IPointOfSale;
    warehouse: IWarehouse;
    seller: IUser;
    document_type: IDocumentType;
    payment_term: IPaymentTerm;
    products: ISaleProduct[];
    payments: ISalePayment[];
    instalments: ISaleInstalment[];
};